# Generated by Django 3.2.9 on 2021-11-02 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, verbose_name='image_path')),
                ('image_file', models.ImageField(upload_to='images/%d_%m_%Y_%H_%M_%S/')),
            ],
        ),
    ]
