# Generated by Django 3.2.9 on 2022-01-27 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='blurred_image_file',
            field=models.ImageField(blank=True, null=True, upload_to='images/%d_%m_%Y_%H_%M_%S/blurred/'),
        ),
        migrations.AddField(
            model_name='image',
            name='blurred_path',
            field=models.CharField(max_length=255, null=True, verbose_name='blurred_path'),
        ),
        migrations.AddField(
            model_name='image',
            name='detected_image_file',
            field=models.ImageField(blank=True, null=True, upload_to='images/%d_%m_%Y_%H_%M_%S/detected/'),
        ),
        migrations.AddField(
            model_name='image',
            name='detected_path',
            field=models.CharField(max_length=255, null=True, verbose_name='detected_path'),
        ),
        migrations.AddField(
            model_name='image',
            name='edges_image_file',
            field=models.ImageField(blank=True, null=True, upload_to='images/%d_%m_%Y_%H_%M_%S/edges/'),
        ),
        migrations.AddField(
            model_name='image',
            name='edges_path',
            field=models.CharField(max_length=255, null=True, verbose_name='edges_path'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='images/%d_%m_%Y_%H_%M_%S/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='path',
            field=models.CharField(max_length=255, null=True, verbose_name='path'),
        ),
    ]
